language: ruby
before_script:
  - "createdb lhm"
rvm:
  - 2.0.0
  - 2.1
  - 2.2
sudo: false
gemfile:
  - gemfiles/ar-2.3_mysql.gemfile
  - gemfiles/ar-3.2_mysql.gemfile
  - gemfiles/ar-3.2_mysql2.gemfile
  - gemfiles/ar-4.0_mysql2.gemfile
  - gemfiles/ar-4.1_mysql2.gemfile
  - gemfiles/ar-4.2_mysql2.gemfile
matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/ar-3.2_mysql.gemfile
    - rvm: 2.2
      gemfile: gemfiles/ar-2.3_mysql.gemfile
